# 构建阶段
FROM node:14.21.3 AS build

WORKDIR /app

COPY ../domain-chatvrm .

RUN npm config set registry https://registry.npmmirror.com && \
    npm install && \
    npm run build --no-lint


# 生产阶段  
FROM node:14.21.3-slim

WORKDIR /app

COPY --from=build /app/.next ./.next
COPY --from=build /app/next.config.js ./
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./

RUN npm install --production

EXPOSE 3000

CMD ["npm", "run", "start"]