# 使用Python 3.10.12作为基础镜像
FROM python:3.10.12

# 设置工作目录
WORKDIR /app

# 复制应用程序文件到工作目录
COPY ../domain-chatbot .
# 安装项目依赖框架
# 使用清华源安装依赖包
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt && \
    rm -rf ~/.cache/pip && \
    rm -rf /tmp/* && \
    python manage.py makemigrations && \
    python manage.py migrate

ENV OPENAI_API_KEY=sk-xxxxx
ENV B_STATION_ID=xxxx
ENV B_UID=12xx
ENV TIMEZONE=Asia/Shanghai

# 暴露应用程序监听的端口
EXPOSE 8000

# 启动Python应用程序，并使用 0.0.0.0:8000 监听所有可用地址
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]