# 使用Node.js 14.21.3作为基础镜像
FROM node:14.21.3

# 设置工作目录
WORKDIR /app

# 复制应用程序到工作目录
COPY ../domain-chatvrm .

RUN npm config set registry https://registry.npmmirror.com

# 安装Node.js依赖项
RUN npm install

# 编译程序
RUN npm run build --no-lint

# 暴露应用程序监听的端口
EXPOSE 3000

# 启动Node.js应用程序
CMD ["npm", "run","start"]
