# 使用Python 3.9.6作为基础镜像
FROM python:3.9.6

# 设置工作目录
WORKDIR /app

# 复制应用程序文件到工作目录
COPY ../domain-chatbot .

# 安装项目依赖框架
RUN pip install -r requirements.txt

# 暴露应用程序监听的端口
EXPOSE 8000

# 启动Python应用程序，并使用 0.0.0.0:8000 监听所有可用地址
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]