# Generated by Django 4.2.1 on 2023-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='比赛结束时间'),
        ),
    ]
