# Generated by Django 4.2.1 on 2023-06-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_riddle_riddle_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionrecord',
            name='competition_id',
            field=models.BigIntegerField(verbose_name='比赛ID'),
        ),
    ]
