# Generated by Django 4.2.1 on 2023-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_competitionrecord_competition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='riddle_count',
            field=models.IntegerField(default=0, verbose_name='谜语字数'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='riddle_description',
            field=models.CharField(max_length=300, verbose_name='谜语描述'),
        ),
    ]
