# Generated by Django 4.2.1 on 2023-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('persona', models.TextField()),
                ('personality', models.TextField()),
                ('scenario', models.TextField()),
                ('examples_of_dialogue', models.TextField()),
                ('custom_role_template_type', models.CharField(max_length=50)),
            ],
        ),
    ]
