# Generated by Django 4.2.1 on 2023-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmemorymodel',
            name='sender',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='localmemorymodel',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
