# Generated by Django 4.2.1 on 2023-09-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_localmemorymodel_sender_alter_localmemorymodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='background/')),
            ],
        ),
    ]
