# Generated by Django 4.2.1 on 2023-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_backgroundimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('original_name', models.CharField(max_length=50)),
                ('vrm_url', models.ImageField(upload_to='vrm/')),
            ],
        ),
    ]
