# Generated by Django 4.2.1 on 2023-09-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_vrmmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vrmmodel',
            old_name='vrm_url',
            new_name='vrm',
        ),
    ]
