# Generated by Django 4.2.1 on 2023-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_vrm_url_vrmmodel_vrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrmmodel',
            name='vrm',
            field=models.FileField(upload_to='vrm/'),
        ),
    ]
