# Generated by Django 4.2.1 on 2024-01-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_vrmmodel_vrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigIntegerField(db_comment='门户用户唯一ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='门户用户名称', max_length=100)),
            ],
        ),
    ]
