



import os
import requests
from ..utils.uuid_generator import generate


url = 'https://genshinvoice.top/api'
headers = {
    'accept': '*/*',
    'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
    'referer': 'https://genshinvoice.top/v2/',
    'sec-ch-ua': '"Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'audio',
    'sec-fetch-mode': 'no-cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'
}

bert_vits2_voices = [
  {"id": "丹恒", "name": "丹恒"},
  {"id": "克拉拉", "name": "克拉拉"},
  {"id": "穹", "name": "穹"},
  {"id": "「信使」", "name": "「信使」"},
  {"id": "史瓦罗", "name": "史瓦罗"},
  {"id": "彦卿", "name": "彦卿"},
  {"id": "晴霓", "name": "晴霓"},
  {"id": "杰帕德", "name": "杰帕德"},
  {"id": "素裳", "name": "素裳"},
  {"id": "绿芙蓉", "name": "绿芙蓉"},
  {"id": "罗刹", "name": "罗刹"},
  {"id": "艾丝妲", "name": "艾丝妲"},
  {"id": "黑塔", "name": "黑塔"},
  {"id": "丹枢", "name": "丹枢"},
  {"id": "希露瓦", "name": "希露瓦"},
  {"id": "白露", "name": "白露"},
  {"id": "费斯曼", "name": "费斯曼"},
  {"id": "停云", "name": "停云"},
  {"id": "可可利亚", "name": "可可利亚"},
  {"id": "景元", "name": "景元"},
  {"id": "螺丝咕姆", "name": "螺丝咕姆"},
  {"id": "青镞", "name": "青镞"},
  {"id": "公输师傅", "name": "公输师傅"},
  {"id": "卡芙卡", "name": "卡芙卡"},
  {"id": "大毫", "name": "大毫"},
  {"id": "驭空", "name": "驭空"},
  {"id": "半夏", "name": "半夏"},
  {"id": "奥列格", "name": "奥列格"},
  {"id": "娜塔莎", "name": "娜塔莎"},
  {"id": "桑博", "name": "桑博"},
  {"id": "瓦尔特", "name": "瓦尔特"},
  {"id": "阿兰", "name": "阿兰"},
  {"id": "伦纳德", "name": "伦纳德"},
  {"id": "佩拉", "name": "佩拉"},
  {"id": "卡波特", "name": "卡波特"},
  {"id": "帕姆", "name": "帕姆"},
  {"id": "帕斯卡", "name": "帕斯卡"},
  {"id": "青雀", "name": "青雀"},
  {"id": "三月七", "name": "三月七"},
  {"id": "刃", "name": "刃"},
  {"id": "姬子", "name": "姬子"},
  {"id": "布洛妮娅", "name": "布洛妮娅"},
  {"id": "希儿", "name": "希儿"},
  {"id": "星", "name": "星"},
  {"id": "符玄", "name": "符玄"},
  {"id": "虎克", "name": "虎克"},
  {"id": "银狼", "name": "银狼"},
  {"id": "镜流", "name": "镜流"},
  {"id": "「博士」", "name": "「博士」"},
  {"id": "「大肉丸」", "name": "「大肉丸」"},
  {"id": "九条裟罗", "name": "九条裟罗"},
  {"id": "佐西摩斯", "name": "佐西摩斯"},
  {"id": "刻晴", "name": "刻晴"},
  {"id": "博易", "name": "博易"},
  {"id": "卡维", "name": "卡维"},
  {"id": "可莉", "name": "可莉"},
  {"id": "嘉玛", "name": "嘉玛"},
  {"id": "埃舍尔", "name": "埃舍尔"},
  {"id": "塔杰·拉德卡尼", "name": "塔杰·拉德卡尼"},
  {"id": "大慈树王", "name": "大慈树王"},
  {"id": "宵宫", "name": "宵宫"},
  {"id": "康纳", "name": "康纳"},
  {"id": "影", "name": "影"},
  {"id": "枫原万叶", "name": "枫原万叶"},
  {"id": "欧菲妮", "name": "欧菲妮"},
  {"id": "玛乔丽", "name": "玛乔丽"},
  {"id": "珊瑚", "name": "珊瑚"},
  {"id": "田铁嘴", "name": "田铁嘴"},
  {"id": "砂糖", "name": "砂糖"},
  {"id": "神里绫华", "name": "神里绫华"},
  {"id": "罗莎莉亚", "name": "罗莎莉亚"},
  {"id": "荒泷一斗", "name": "荒泷一斗"},
  {"id": "莎拉", "name": "莎拉"},
  {"id": "迪希雅", "name": "迪希雅"},
  {"id": "钟离", "name": "钟离"},
  {"id": "阿圆", "name": "阿圆"},
  {"id": "阿娜耶", "name": "阿娜耶"},
  {"id": "阿拉夫", "name": "阿拉夫"},
  {"id": "雷泽", "name": "雷泽"},
  {"id": "香菱", "name": "香菱"},
  {"id": "龙二", "name": "龙二"},
  {"id": "「公子」", "name": "「公子」"},
  {"id": "「白老先生」", "name": "「白老先生」"},
  {"id": "优菈", "name": "优菈"},
  {"id": "凯瑟琳", "name": "凯瑟琳"},
  {"id": "哲平", "name": "哲平"},
  {"id": "夏洛蒂", "name": "夏洛蒂"},
  {"id": "安柏", "name": "安柏"},
  {"id": "巴达维", "name": "巴达维"},
  {"id": "式大将", "name": "式大将"},
  {"id": "斯坦利", "name": "斯坦利"},
  {"id": "毗伽尔", "name": "毗伽尔"},
  {"id": "海妮耶", "name": "海妮耶"},
  {"id": "爱德琳", "name": "爱德琳"},
  {"id": "纳西妲", "name": "纳西妲"},
  {"id": "老孟", "name": "老孟"},
  {"id": "芙宁娜", "name": "芙宁娜"},
  {"id": "阿守", "name": "阿守"},
  {"id": "阿祇", "name": "阿祇"},
  {"id": "丹吉尔", "name": "丹吉尔"},
  {"id": "丽莎", "name": "丽莎"},
  {"id": "五郎", "name": "五郎"},
  {"id": "元太", "name": "元太"},
  {"id": "克列门特", "name": "克列门特"},
  {"id": "克罗索", "name": "克罗索"},
  {"id": "北斗", "name": "北斗"},
  {"id": "埃勒曼", "name": "埃勒曼"},
  {"id": "天目十五", "name": "天目十五"},
  {"id": "奥兹", "name": "奥兹"},
  {"id": "恶龙", "name": "恶龙"},
  {"id": "早柚", "name": "早柚"},
  {"id": "杜拉夫", "name": "杜拉夫"},
  {"id": "松浦", "name": "松浦"},
  {"id": "柊千里", "name": "柊千里"},
  {"id": "甘雨", "name": "甘雨"},
  {"id": "石头", "name": "石头"},
  {"id": "纯水精灵？", "name": "纯水精灵？"},
  {"id": "羽生田千鹤", "name": "羽生田千鹤"},
  {"id": "莱依拉", "name": "莱依拉"},
  {"id": "菲谢尔", "name": "菲谢尔"},
  {"id": "言笑", "name": "言笑"},
  {"id": "诺艾尔", "name": "诺艾尔"},
  {"id": "赛诺", "name": "赛诺"},
  {"id": "辛焱", "name": "辛焱"},
  {"id": "迪娜泽黛", "name": "迪娜泽黛"},
  {"id": "那维莱特", "name": "那维莱特"},
  {"id": "八重神子", "name": "八重神子"},
  {"id": "凯亚", "name": "凯亚"},
  {"id": "吴船长", "name": "吴船长"},
  {"id": "埃德", "name": "埃德"},
  {"id": "天叔", "name": "天叔"},
  {"id": "女士", "name": "女士"},
  {"id": "恕筠", "name": "恕筠"},
  {"id": "提纳里", "name": "提纳里"},
  {"id": "派蒙", "name": "派蒙"},
  {"id": "流浪者", "name": "流浪者"},
  {"id": "深渊使徒", "name": "深渊使徒"},
  {"id": "玛格丽特", "name": "玛格丽特"},
  {"id": "珐露珊", "name": "珐露珊"},
  {"id": "琴", "name": "琴"},
  {"id": "瑶瑶", "name": "瑶瑶"},
  {"id": "留云借风真君", "name": "留云借风真君"},
  {"id": "绮良良", "name": "绮良良"},
  {"id": "舒伯特", "name": "舒伯特"},
  {"id": "荧", "name": "荧"},
  {"id": "莫娜", "name": "莫娜"},
  {"id": "行秋", "name": "行秋"},
  {"id": "迈勒斯", "name": "迈勒斯"},
  {"id": "阿佩普", "name": "阿佩普"},
  {"id": "鹿野奈奈", "name": "鹿野奈奈"},
  {"id": "七七", "name": "七七"},
  {"id": "伊迪娅", "name": "伊迪娅"},
  {"id": "博来", "name": "博来"},
  {"id": "坎蒂丝", "name": "坎蒂丝"},
  {"id": "埃尔欣根", "name": "埃尔欣根"},
  {"id": "埃泽", "name": "埃泽"},
  {"id": "塞琉斯", "name": "塞琉斯"},
  {"id": "夜兰", "name": "夜兰"},
  {"id": "常九爷", "name": "常九爷"},
  {"id": "悦", "name": "悦"},
  {"id": "戴因斯雷布", "name": "戴因斯雷布"},
  {"id": "笼钓瓶一心", "name": "笼钓瓶一心"},
  {"id": "纳比尔", "name": "纳比尔"},
  {"id": "胡桃", "name": "胡桃"},
  {"id": "艾尔海森", "name": "艾尔海森"},
  {"id": "艾莉丝", "name": "艾莉丝"},
  {"id": "菲米尼", "name": "菲米尼"},
  {"id": "蒂玛乌斯", "name": "蒂玛乌斯"},
  {"id": "迪奥娜", "name": "迪奥娜"},
  {"id": "阿晃", "name": "阿晃"},
  {"id": "阿洛瓦", "name": "阿洛瓦"},
  {"id": "陆行岩本真蕈·元素生命", "name": "陆行岩本真蕈·元素生命"},
  {"id": "雷电将军", "name": "雷电将军"},
  {"id": "魈", "name": "魈"},
  {"id": "鹿野院平藏", "name": "鹿野院平藏"},
  {"id": "「女士」", "name": "「女士」"},
  {"id": "「散兵」", "name": "「散兵」"},
  {"id": "丽晶", "name": "丽晶"},
  {"id": "八重樱", "name": "八重樱"},
  {"id": "剑士", "name": "剑士"},
  {"id": "千子村正", "name": "千子村正"},
  {"id": "千岛", "name": "千岛"},
  {"id": "可蕾", "name": "可蕾"},
  {"id": "吴绳", "name": "吴绳"},
  {"id": "四郎切", "name": "四郎切"},
  {"id": "嘉然", "name": "嘉然"},
  {"id": "国士无双", "name": "国士无双"},
  {"id": "均一", "name": "均一"},
  {"id": "墨家刺客", "name": "墨家刺客"},
  {"id": "大墨判", "name": "大墨判"},
  {"id": "女式面具刺客", "name": "女式面具刺客"},
  {"id": "安", "name": "安"},
  {"id": "寻风者", "name": "寻风者"},
  {"id": "常驻", "name": "常驻"},
  {"id": "左旋", "name": "左旋"},
  {"id": "布鲁诺", "name": "布鲁诺"},
  {"id": "杜卡曼", "name": "杜卡曼"},
  {"id": "河长官", "name": "河长官"},
  {"id": "洗衣妇", "name": "洗衣妇"},
  {"id": "王文远", "name": "王文远"},
  {"id": "甘", "name": "甘"},
  {"id": "留才", "name": "留才"},
  {"id": "羽良多", "name": "羽良多"},
  {"id": "荒脊晶", "name": "荒脊晶"},
  {"id": "莉莉娅", "name": "莉莉娅"},
  {"id": "达奥林", "name": "达奥林"},
  {"id": "骑士", "name": "骑士"}
]


class BertVits2API():

    def request(params:dict[str,str]) -> str:
        
        # 发送请求合成语音
        response = requests.get(url, headers=headers, params=params)

        # 初始化文件夹
        file_name = generate() + ".wav"
        file_path = os.getcwd() + "/tmp/" + file_name
        dirPath = os.path.dirname(file_path)
        if not os.path.exists(dirPath):
            os.makedirs(dirPath)
        if not os.path.exists(file_path):
            # 用open创建文件 兼容mac
            open(file_path, 'a').close()

        # 写入语音文件
        with open(file_path, 'wb') as file:
            file.write(response.content)

        return file_name
        

class BertVits2():

    def synthesis(text: str, speaker: str, noise: str, noisew: str, sdp_ratio: str) -> str:
        params = {
            'speaker': speaker,
            'text': text,
            'format': "wav",
            'length': '1',
            'noise': noise,
            'noisew': noisew,
            'sdp_ratio': sdp_ratio
        }
        return BertVits2API.request(params=params)

    def get_voices() -> list:
        return bert_vits2_voices
